import * as path from "node:path";
import * as fs from "node:fs/promises";
import * as vscode from "vscode";

const SKILL_REL = path.join(".claude", "skills", "arduino-cli");
const SKILL_FILES = ["SKILL.md", "reference.md"];
// Namespaced Copilot instructions file (not the shared, single
// `.github/copilot-instructions.md`, which the user/other tools may own).
const COPILOT_REL = path.join(".github", "instructions", "arduino-cli.instructions.md");

/**
 * Set up the shared AI-assistant config for this workspace from ONE source of
 * truth (`.claude/skills/arduino-cli/reference.md`, shipped in the .vsix):
 *
 *  - Claude Code: copies the skill (`SKILL.md` + `reference.md`) into
 *    `.claude/skills/arduino-cli/`; a session here discovers it.
 *  - GitHub Copilot (agent mode): writes `reference.md`, wrapped in an
 *    `applyTo` front-matter, to `.github/instructions/arduino-cli.instructions.md`,
 *    which Copilot auto-loads. (Copilot has no lazy "read another file" step, so
 *    the content is inlined rather than pointed at.)
 *
 * Both hosts then drive `arduino-cli` via the shell — no wrapper tools.
 */
export async function installAiAssistants(
  context: vscode.ExtensionContext,
): Promise<void> {
  const root = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
  if (!root) {
    vscode.window.showWarningMessage(
      vscode.l10n.t("Open a workspace folder first to install the Arduino skill."),
    );
    return;
  }

  try {
    // Claude Code skill.
    const srcDir = path.join(context.extensionPath, SKILL_REL);
    const destDir = path.join(root, SKILL_REL);
    await fs.mkdir(destDir, { recursive: true });
    for (const file of SKILL_FILES) {
      await fs.copyFile(path.join(srcDir, file), path.join(destDir, file));
    }

    // Copilot instructions: same reference.md, wrapped with an applyTo header.
    const reference = await fs.readFile(
      path.join(srcDir, "reference.md"),
      "utf8",
    );
    const copilotDest = path.join(root, COPILOT_REL);
    await fs.mkdir(path.dirname(copilotDest), { recursive: true });
    await fs.writeFile(
      copilotDest,
      `---\napplyTo: "**"\n---\n<!-- Generated by the Arduino CLI extension from the shared reference.md. Edit there. -->\n\n${reference}`,
    );
  } catch (err) {
    vscode.window.showErrorMessage(
      vscode.l10n.t(
        "Could not install the Arduino skill: {0}",
        err instanceof Error ? err.message : String(err),
      ),
    );
    return;
  }

  vscode.window.showInformationMessage(
    vscode.l10n.t(
      "Arduino AI assistant configured: GitHub Copilot instructions and Claude Code skill installed in this folder.",
    ),
  );
}
